server:
  port: 5000
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri:
            lb://USER-SERVICE
          predicates:
            - Path=/auth/**,/users/**,/api/users/**,/
        - id: Task-SERVICE
          uri:
            lb://Task-SERVICE
          predicates:
            - Path=/api/tasks/**,/tasks/**
        - id: SUBMISSION-SERVICE
          uri:
            lb://SUBMISSION-SERVICE
          predicates:
            - Path=/api/submissions/**,/submissions/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

